### ISSUE TITLE
Please clean up your requirements. This one's got more than 200.

### ISSUE THREAD

**Issue by amcgregor** [kevinadhiguna/secret-image-keeper#1]
Exactly the same problem as per: kevinadhiguna/link-shortener#1 and kevinadhiguna/instagram-profpic-downloader#1 and kevinadhiguna/body-mass-index-calculator#1 and kevinadhiguna/ip-revealer#1 … the list has become long enough to not even include all. See the first referenced here for a full index of how bad this problem is.

Low quality bulk library creation with no use of the referenced libraries is pure spam.  Please correct this.

**Comment by kevinadhiguna** [comment]
Hello @amcgregor , thank you for this report. As this app imports tkinter, I decided not to generate `requirements.txt`. 

Reference : [install tkinter for python](https://stackoverflow.com/questions/4783810/install-tkinter-for-python)
> You don't need to download Tkinter - it's an integral part of all Python distributions (except binary distributions for platforms that don't support Tcl/Tk).

Should you have any questions, please feel free to ask. Thank you !

**Comment by amcgregor** [comment]
Thank you very much, and apologies for the cross-project e-mail notification spam I must have triggered; thought you may wish to individually track corrections.

Thank you again! (Time for another spam-wave. 😭) Wave 2! 😀
